#!/bin/bash

valid_versions=("12" "13")

if [[ ! " ${valid_versions[@]} " =~ " $1 " ]]; then
  echo "Invalid version. Please use one of the following: ${valid_versions[@]}"
  exit 1
fi

composer remove typo3/cms-dashboard -n -d /var/www/html/v$1
