services:
    docs:
        image: ghcr.io/t3docs/render-documentation:latest
        command: makehtml
        volumes:
            - ../:/PROJECT:ro
            - ../Documentation-GENERATED-temp:/RESULT
